//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BannerlordCoopInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BannerlordCoopInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] _0harmony {
            get {
                object obj = ResourceManager.GetObject("_0harmony", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon bannerlord_icon {
            get {
                object obj = ResourceManager.GetObject("bannerlord_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BannerlordSystemTestingFramework {
            get {
                object obj = ResourceManager.GetObject("BannerlordSystemTestingFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Common {
            get {
                object obj = ResourceManager.GetObject("Common", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Coop {
            get {
                object obj = ResourceManager.GetObject("Coop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Prefab&gt;
        ///  &lt;Window&gt;
        ///    &lt;Widget WidthSizePolicy=&quot;StretchToParent&quot; HeightSizePolicy=&quot;StretchToParent&quot;&gt;
        ///      &lt;Children&gt;
        ///        &lt;Standard.Background/&gt;
        ///
        ///        &lt;Standard.TopPanel Parameter.Title=&quot;@MovieTextHeader&quot;/&gt;
        ///
        ///        &lt;ListPanel DoNotAcceptEvents=&quot;false&quot; WidthSizePolicy=&quot;CoverChildren&quot; HeightSizePolicy=&quot;CoverChildren&quot;
        ///                   HorizontalAlignment=&quot;Center&quot; VerticalAlignment=&quot;Center&quot; MarginTop=&quot;-300&quot;
        ///                   LayoutImp.LayoutMethod=&quot;HorizontalLeftToRight&quot;&gt;
        ///          &lt;Child [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CoopConnectionUIMovie {
            get {
                return ResourceManager.GetString("CoopConnectionUIMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CoopFramework {
            get {
                object obj = ResourceManager.GetObject("CoopFramework", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DistributedLock {
            get {
                object obj = ResourceManager.GetObject("DistributedLock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Extensions_Data_xxHash {
            get {
                object obj = ResourceManager.GetObject("Extensions_Data_xxHash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Launcher {
            get {
                object obj = ResourceManager.GetObject("Launcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LiteNetLib {
            get {
                object obj = ResourceManager.GetObject("LiteNetLib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Mono_Reflection {
            get {
                object obj = ResourceManager.GetObject("Mono_Reflection", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Network {
            get {
                object obj = ResourceManager.GetObject("Network", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NLog {
            get {
                object obj = ResourceManager.GetObject("NLog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RailgunNet {
            get {
                object obj = ResourceManager.GetObject("RailgunNet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RemoteAction {
            get {
                object obj = ResourceManager.GetObject("RemoteAction", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SimpleTCP {
            get {
                object obj = ResourceManager.GetObject("SimpleTCP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Stateless {
            get {
                object obj = ResourceManager.GetObject("Stateless", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Module&gt;
        ///    &lt;Name value=&quot;Coop&quot;/&gt;
        ///    &lt;Id value=&quot;Coop&quot;/&gt;
        ///    &lt;Version value=&quot;v0.0.1&quot;/&gt;
        ///    &lt;SingleplayerModule value=&quot;true&quot;/&gt;
        ///    &lt;MultiplayerModule value=&quot;false&quot;/&gt;
        ///    &lt;DependedModules&gt;
        ///        &lt;DependedModule Id=&quot;Native&quot; DependentVersion=&quot;e1.6.1&quot;/&gt;
        ///        &lt;DependedModule Id=&quot;SandBoxCore&quot; DependentVersion=&quot;e1.6.1&quot;/&gt;
        ///        &lt;DependedModule Id=&quot;Sandbox&quot; DependentVersion=&quot;e1.6.1&quot;/&gt;
        ///        &lt;DependedModule Id=&quot;CustomBattle&quot; DependentVersion=&quot;e1.6.1&quot;/&gt;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SubModule {
            get {
                return ResourceManager.GetString("SubModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
