name: Build and Test

on: 
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: garrettluskey/bannerlordcoop:v1.1.4
      
    steps:
      - name: Checkout Repo
        run: |
          git clone https://github.com/${{ github.repository }}
          cd BannerlordCoop
          git checkout "${{ github.ref_name }}"

      - name: Link Game Assemblies Folder
        run: |
          ln -s /home/mb2 BannerlordCoop
          
      - name: Build Solution
        run: |
          cd BannerlordCoop/source
          dotnet build
          
      - name: Run Unit Tests
        run: |
          cd BannerlordCoop/source
          dotnet test